### ISSUE TITLE
I cannot run

### ISSUE THREAD

**Issue by acseckin** [georgeBoole/biofeedback#1]
Hi,
I try to run biofeedback with windows 7, pythonxy ide (installed mindcontrol module), and mindwave mobile (connected to COM3 serial port) it gives this errors:

Python 2.7.5 (default, May 15 2013, 22:43:36) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.

Imported NumPy 1.7.1, SciPy 0.12.0, Matplotlib 1.2.1 + guidata 1.6.1, guiqwt 2.3.1
Type "scientific" for more details.

> > > runfile(r'C:\Python27\Scripts\biofeedback-master\version1\biofeedback.py', wdir=r'C:\Python27\Scripts\biofeedback-master\version1')
> > > Exception in thread Thread-2:
> > > Traceback (most recent call last):
> > >   File "C:\Python27\lib\threading.py", line 808, in __bootstrap_inner
> > >     self.run()
> > >   File "C:\Python27\lib\threading.py", line 761, in run
> > >     self.__target(_self.__args, *_self.__kwargs)
> > >   File "C:\Python27\lib\site-packages\mindcontrol-0.7dev-py2.7.egg\mindcontrol\userbrain.py", line 107, in _processDataStream
> > >     raw_data = json_processor()
> > >   File "C:\Python27\lib\site-packages\mindcontrol-0.7dev-py2.7.egg\mindcontrol\userbrain.py", line 103, in <lambda>
> > >     json_processor = lambda: ds.next()
> > >   File "C:\Python27\lib\site-packages\mindcontrol-0.7dev-py2.7.egg\mindcontrol\userbrain.py", line 75, in _datastream
> > >     cs.connect((host, port))
> > >   File "C:\Python27\lib\socket.py", line 224, in meth
> > >     return getattr(self._sock,name)(*args)
> > > error: [Errno 10061] connection not established because of target machine denys actively

**Comment by georgeBoole** [comment]
Do you have Python built with threading? Try "import thread" and see if it works

**Comment by acseckin** [comment]
import thread not fix the problem

![image](https://f.cloud.github.com/assets/3118166/806663/b846cb96-ee3f-11e2-9f6b-7524346e43bb.png)
